name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build-1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip-v: true
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}
      
    - name: Build and push image-judger
      uses: docker/build-push-action@v2
      with:
        context: ./judger
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERUSERNAME }}/image-judger:${{steps.tag.outputs.tag}} ${{ secrets.DOCKERUSERNAME }}/image-judger:latest
        
  build-2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip-v: true
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Build and push image-judger-scheduler
      uses: docker/build-push-action@v2
      with:
        context: ./judger-scheduler
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERUSERNAME }}/image-judger-scheduler:${{steps.tag.outputs.tag}} ${{ secrets.DOCKERUSERNAME }}/image-judger-scheduler:latest
        
        
  build-3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip-v: true
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}
    
    - name: Build and push image-web-service
      uses: docker/build-push-action@v2
      with:
        context: ./web-service
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERUSERNAME }}/image-web-service:${{steps.tag.outputs.tag}} ${{ secrets.DOCKERUSERNAME }}/image-web-service:latest
