name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image-judger
      run: docker build ./judger --tag image-judger:$(date +%s)
    - name: Build image-judger-scheduler
      run: docker build ./judger-scheduler --tag image-judger-scheduler:$(date +%s)
    - name: Build image-web-service
      run: docker build ./web-service --tag image-web-service:$(date +%s)
