name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}
      
    - name: Build and push image-judger
      uses: docker/build-push-action@v2
      with:
        context: ./judger
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERUSERNAME }}/image-judger:${{ steps.previoustag.outputs.tag }}
    - name: Build and push image-judger-scheduler
      uses: docker/build-push-action@v2
      with:
        context: ./judger-scheduler
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERUSERNAME }}/image-judger-scheduler:${{ steps.previoustag.outputs.tag }}
    - name: Build and push image-web-service
      uses: docker/build-push-action@v2
      with:
        context: ./web-service
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKERUSERNAME }}/image-web-service:${{ steps.previoustag.outputs.tag }}
